-- ===================================================================
-- BOOKING_LOCATIONS: MANY-TO-MANY JOIN TABLE (replaces bookings.location_id CSV)
-- Run this script in the Supabase SQL Editor (https://supabase.com)
--
-- Replaces the comma-separated bookings.location_id string with a proper
-- join table. See booking_locations_migration.sql history / PR description
-- for background. Do NOT run the final DROP COLUMN statement at the bottom
-- until every application code path has been deployed and verified against
-- this table.
-- ===================================================================

-- 1. Create the join table.
--    No FK to locations(id): it is unconfirmed whether location ids are
--    globally unique or only unique per dataset (DEV vs LIVE), so this
--    table does not depend on that. The one-location-one-booking invariant
--    is enforced below by a trigger scoped by dataset instead.
CREATE TABLE IF NOT EXISTS booking_locations (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id   text NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    location_id  text NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT booking_locations_unique_pair UNIQUE (booking_id, location_id)
);

CREATE INDEX IF NOT EXISTS idx_booking_locations_booking_id ON booking_locations (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_locations_location_id ON booking_locations (location_id);

-- 2. Backfill from the existing CSV column.
--    regexp_split_to_table handles ", " / "," / extra whitespace; DISTINCT
--    guards against accidental duplicate tokens like "A12, A12".
INSERT INTO booking_locations (booking_id, location_id)
SELECT DISTINCT b.id, trim(loc)
FROM bookings b,
     LATERAL regexp_split_to_table(b.location_id, '\s*,\s*') AS loc
WHERE b.location_id IS NOT NULL
  AND trim(loc) <> ''
ON CONFLICT (booking_id, location_id) DO NOTHING;

-- 3. Enforce "a location can only belong to one Confirmed booking within the
--    same dataset (DEV vs LIVE)". Dataset is derived from bookings.instance_prefix
--    (a value the app fully controls), not from locations.id, since that
--    column's global uniqueness across datasets is unconfirmed.
CREATE OR REPLACE FUNCTION booking_locations_check_conflict() RETURNS trigger AS $$
DECLARE
    v_new_dataset  text;
    v_conflict_id  text;
BEGIN
    SELECT CASE WHEN instance_prefix LIKE '%-DEV-' THEN 'DEV' ELSE 'LIVE' END
      INTO v_new_dataset
    FROM bookings WHERE id = NEW.booking_id;

    SELECT bl.booking_id INTO v_conflict_id
    FROM booking_locations bl
    JOIN bookings b2 ON b2.id = bl.booking_id
    WHERE bl.location_id = NEW.location_id
      AND bl.booking_id <> NEW.booking_id
      AND b2.status = 'Confirmed'
      AND (CASE WHEN b2.instance_prefix LIKE '%-DEV-' THEN 'DEV' ELSE 'LIVE' END) = v_new_dataset
    LIMIT 1;

    IF v_conflict_id IS NOT NULL THEN
        RAISE EXCEPTION 'Location % is already assigned to booking %', NEW.location_id, v_conflict_id
            USING ERRCODE = 'unique_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_booking_locations_check_conflict ON booking_locations;
CREATE TRIGGER trg_booking_locations_check_conflict
    BEFORE INSERT OR UPDATE ON booking_locations
    FOR EACH ROW EXECUTE FUNCTION booking_locations_check_conflict();

-- 4. Atomic "replace all locations for a booking" RPC. Supabase JS has no
--    multi-table client transactions, and both the admin UI (multi-location
--    replace) and the steward tool (single-location replace) perform the
--    same logical operation, so this is the single write path for both.
--    SECURITY DEFINER so it can run under one fixed role check rather than
--    depending on booking_locations' own per-caller RLS grants.
CREATE OR REPLACE FUNCTION rpc_set_booking_locations(p_booking_id text, p_location_ids text[])
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM user_roles
        WHERE user_roles.id = auth.uid() AND user_roles.role IN ('admin', 'steward')
    ) THEN
        RAISE EXCEPTION 'Not authorized';
    END IF;

    DELETE FROM booking_locations WHERE booking_id = p_booking_id;

    INSERT INTO booking_locations (booking_id, location_id)
    SELECT p_booking_id, loc
    FROM unnest(p_location_ids) AS loc
    WHERE loc IS NOT NULL AND trim(loc) <> '';
END;
$$;

REVOKE ALL ON FUNCTION rpc_set_booking_locations(text, text[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION rpc_set_booking_locations(text, text[]) TO authenticated;

-- 5. RLS — same convention as secure_settings_policy.sql (enable RLS,
--    drop-then-recreate named policies, narrow anon SELECT, admin FOR ALL
--    gated on user_roles).
ALTER TABLE booking_locations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public anon to read confirmed booking locations" ON booking_locations;
DROP POLICY IF EXISTS "Allow authenticated read access to booking_locations" ON booking_locations;
DROP POLICY IF EXISTS "Allow admins full access to booking_locations" ON booking_locations;

-- Anon needs SELECT for the public visitor map's direct-query fallback path
-- (fetchMapData in api.js queries booking_locations directly when the
-- visitor-map Edge Function is unavailable or for unauthenticated viewers).
CREATE POLICY "Allow public anon to read confirmed booking locations"
ON booking_locations FOR SELECT TO anon
USING (
    EXISTS (
        SELECT 1 FROM bookings
        WHERE bookings.id = booking_locations.booking_id
          AND bookings.status = 'Confirmed'
    )
);

CREATE POLICY "Allow authenticated read access to booking_locations"
ON booking_locations FOR SELECT TO authenticated
USING (true);

-- Table-level writes are intentionally NOT granted to authenticated users
-- (admin or steward) beyond SELECT above — all app writes go through
-- rpc_set_booking_locations(), which is SECURITY DEFINER and does its own
-- role check. This keeps one write path and one place enforcing the
-- one-location-per-booking invariant. This admin policy remains as a
-- dashboard-level escape hatch for manual fixes via the SQL Editor.
CREATE POLICY "Allow admins full access to booking_locations"
ON booking_locations FOR ALL TO authenticated
USING (
    EXISTS (SELECT 1 FROM user_roles WHERE user_roles.id = auth.uid() AND user_roles.role = 'admin')
)
WITH CHECK (
    EXISTS (SELECT 1 FROM user_roles WHERE user_roles.id = auth.uid() AND user_roles.role = 'admin')
);

-- ===================================================================
-- 6. FINAL CUTOVER — only run this after ALL application code has been
--    deployed and verified end-to-end against booking_locations.
-- ===================================================================
-- ALTER TABLE bookings DROP COLUMN location_id;
