-- SMS sending, mirroring the existing email queue pipeline.
--
-- This is the database half of the SMS feature (see the send-sms /
-- queue-bulk-sms / retry-queued-sms Edge Functions and _shared/sms.ts for the
-- sending half). Every design decision here is a deliberate copy of the
-- email_queue / email_templates model so the two paths behave identically and
-- there's one mental model to maintain:
--
--   email_queue    -> sms_queue        (outbound send log + work queue)
--   email_templates-> sms_templates    (admin-editable message bodies)
--   claim_pending_emails() -> claim_pending_sms()  (batch drain claimer)
--
-- Provider-agnostic by design: nothing in the schema names a specific SMS
-- provider. Which provider actually sends (mock / thesmsworks / twilio / ...)
-- is chosen at runtime from the `settings` table (sms_provider + credentials),
-- exactly like the Zoho email credentials already live there. Default provider
-- is 'mock', so the whole pipeline runs end-to-end with no account signed up:
-- rows flow Pending -> Sent, just with a no-op send.

-- ---------------------------------------------------------------------------
-- sms_queue — one row per outbound text, same shape as email_queue.
--   status: 'Pending' -> 'Processing' -> 'Sent' | 'Error'
--   segments: how many 160/153-char (or 70/67 for unicode) parts the body
--             takes — recorded for cost visibility, since unlike email each
--             segment is billed.
--   provider_message_id: the id the provider hands back on a successful send
--             (e.g. The SMS Works messageid, Twilio sid) for later reconciliation.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."sms_queue" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "recipient" "text" NOT NULL,
    "body" "text" NOT NULL,
    "status" "text" DEFAULT 'Pending'::"text",
    "error_message" "text",
    "segments" integer,
    "provider_message_id" "text",
    "instance_prefix" "text",
    "claimed_at" timestamp with time zone,
    "retry_count" integer DEFAULT 0 NOT NULL,
    "last_retry_at" timestamp with time zone
);

ALTER TABLE "public"."sms_queue" OWNER TO "postgres";

-- Identity column and primary key, both guarded so this migration can be
-- re-applied over a partially-created table. A half-applied earlier run left
-- sms_queue and its sequence in place on the shared test project, and plain
-- ALTER ... ADD GENERATED / ADD CONSTRAINT both hard-error on "already exists"
-- (there is no IF NOT EXISTS form for either), which stalled the re-push.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.sms_queue'::regclass
      AND attname = 'id'
      AND attidentity <> ''
  ) THEN
    -- An orphaned sequence from a half-applied run would collide with the
    -- one ADD GENERATED creates implicitly. Only reachable when the column
    -- is not already an identity column, so this can't drop a live sequence.
    DROP SEQUENCE IF EXISTS "public"."sms_queue_id_seq";
    ALTER TABLE "public"."sms_queue"
      ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."sms_queue_id_seq"
      );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sms_queue'::regclass
      AND contype = 'p'
  ) THEN
    ALTER TABLE ONLY "public"."sms_queue"
      ADD CONSTRAINT "sms_queue_pkey" PRIMARY KEY ("id");
  END IF;
END $$;

COMMENT ON COLUMN "public"."sms_queue"."recipient" IS
  'Destination phone number in E.164 form (e.g. +447700900123). Normalised by the sending Edge Function before insert.';
COMMENT ON COLUMN "public"."sms_queue"."segments" IS
  'Number of billed SMS parts the body encodes to (GSM-7: 160, or 153 when concatenated; UCS-2: 70/67). Recorded for cost visibility.';
COMMENT ON COLUMN "public"."sms_queue"."provider_message_id" IS
  'The message id returned by the SMS provider on a successful send (The SMS Works messageid, Twilio sid, etc.). Null until sent.';
COMMENT ON COLUMN "public"."sms_queue"."retry_count" IS
  'Number of times an admin has manually retried this send via the SMS Queue viewer. 0 = never retried.';
COMMENT ON COLUMN "public"."sms_queue"."last_retry_at" IS
  'When the most recent manual retry was attempted (null if never retried).';

-- ---------------------------------------------------------------------------
-- claim_pending_sms — batch claimer, byte-for-byte the same locking strategy
-- as claim_pending_emails: flip a batch of claimable rows to 'Processing'
-- under FOR UPDATE SKIP LOCKED so concurrent drains never double-send, and
-- self-heal rows stuck 'Processing' for >15 minutes (a crashed drain) back
-- into the workable set.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION "public"."claim_pending_sms"("p_batch_size" integer DEFAULT 50) RETURNS SETOF "public"."sms_queue"
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  UPDATE public.sms_queue
  SET status = 'Processing', claimed_at = now()
  WHERE id IN (
    SELECT id FROM public.sms_queue
    WHERE status = 'Pending'
       OR (status = 'Processing' AND claimed_at < now() - INTERVAL '15 minutes')
    ORDER BY created_at ASC
    LIMIT p_batch_size
    FOR UPDATE SKIP LOCKED
  )
  RETURNING *;
$$;

ALTER FUNCTION "public"."claim_pending_sms"("p_batch_size" integer) OWNER TO "postgres";

-- ---------------------------------------------------------------------------
-- sms_templates — admin-editable message bodies, mirroring email_templates.
-- No subject column (SMS has no subject); body is plain text, not HTML.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "public"."sms_templates" (
    "id" "text" NOT NULL,
    "body" "text" NOT NULL,
    "description" "text",
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "sms_templates_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "public"."sms_templates" OWNER TO "postgres";

COMMENT ON TABLE "public"."sms_templates" IS
  'Admin-editable plain-text SMS message bodies, keyed by a stable id (e.g. booking_confirmed). Mirrors email_templates but has no subject and body is plain text.';

-- ---------------------------------------------------------------------------
-- RLS + grants — identical access model to the email tables.
--
--   sms_queue:     admin-only via RLS policy; service_role ALL (the Edge
--                  Functions run as service_role and bypass RLS);
--                  authenticated gets SELECT+INSERT only (queue a send / read
--                  the viewer) — deliberately NO UPDATE, so status transitions
--                  are service-role/RPC only, exactly as email_queue was
--                  narrowed in 20260718110000. The retry action therefore has
--                  to go through the retry-queued-sms Edge Function.
--   sms_templates: admin manage via RLS; service_role ALL; authenticated
--                  SELECT+UPDATE (edit template text in place, ids are seeded).
--
-- anon gets nothing on either table — this project's ALTER DEFAULT PRIVILEGES
-- no longer auto-grants anon/authenticated on new tables, but the explicit
-- REVOKE keeps the intent auditable (same pattern as google_reviews_cache).
-- ---------------------------------------------------------------------------
ALTER TABLE "public"."sms_queue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."sms_templates" ENABLE ROW LEVEL SECURITY;

-- Dropped first so the migration is re-runnable: CREATE POLICY has no
-- IF NOT EXISTS form and errors on a second apply.
DROP POLICY IF EXISTS "Admin manage sms" ON "public"."sms_queue";
DROP POLICY IF EXISTS "Admin manage sms_templates" ON "public"."sms_templates";

CREATE POLICY "Admin manage sms" ON "public"."sms_queue"
  USING ("public"."check_user_role"('admin'::"public"."user_role"));

CREATE POLICY "Admin manage sms_templates" ON "public"."sms_templates" TO "authenticated"
  USING ((EXISTS ( SELECT 1
     FROM "public"."user_roles"
    WHERE (("user_roles"."id" = "auth"."uid"()) AND ("user_roles"."role" = 'admin'::"public"."user_role")))))
  WITH CHECK ((EXISTS ( SELECT 1
     FROM "public"."user_roles"
    WHERE (("user_roles"."id" = "auth"."uid"()) AND ("user_roles"."role" = 'admin'::"public"."user_role")))));

REVOKE ALL ON TABLE "public"."sms_queue" FROM "anon", "authenticated";
GRANT ALL ON TABLE "public"."sms_queue" TO "service_role";
GRANT SELECT, INSERT ON TABLE "public"."sms_queue" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."sms_queue_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."sms_queue_id_seq" TO "authenticated";

REVOKE ALL ON TABLE "public"."sms_templates" FROM "anon", "authenticated";
GRANT ALL ON TABLE "public"."sms_templates" TO "service_role";
GRANT SELECT, UPDATE ON TABLE "public"."sms_templates" TO "authenticated";

-- The claimer is only ever called by the service-role drain loop; keep execute
-- off anon/authenticated (service_role can execute regardless).
REVOKE ALL ON FUNCTION "public"."claim_pending_sms"("p_batch_size" integer) FROM "anon", "authenticated";

-- ---------------------------------------------------------------------------
-- Seed the settings rows the sending layer reads, so the feature is inert-but-
-- present out of the box: provider 'mock' sends nothing (no account needed),
-- and a placeholder sender id. Swap sms_provider + fill credentials from
-- settings.html once a real provider is chosen. INSERT ... ON CONFLICT DO
-- NOTHING so re-running never clobbers real values later.
-- ---------------------------------------------------------------------------
INSERT INTO "public"."settings" ("key", "value", "updated_by") VALUES
  ('sms_provider',        'mock',       'migration_20260725100000'),
  ('sms_sender_id',       'EllaStFest', 'migration_20260725100000'),
  ('sms_default_country', 'GB',         'migration_20260725100000')
ON CONFLICT ("key") DO NOTHING;

-- Optional seed template so there's something to edit in the viewer.
INSERT INTO "public"."sms_templates" ("id", "body", "description") VALUES
  ('booking_confirmed',
   'Hi {{owner_name}}, your Ella Street Festival stall booking is confirmed. Not monitored for replies - email festival.stalls@ellastreet.co.uk with any questions.',
   'Sent when a booking moves to Confirmed. {{owner_name}} is substituted by the sender.')
ON CONFLICT ("id") DO NOTHING;
